### ISSUE TITLE
ReflexilPlugin, project not loading

### ISSUE THREAD

**Issue by Nonobis** [telerik/justdecompile-plugins#2]
Hello,

in the reflexil plugin, i have error in project file 'Reflexil.JustDecompile.Module.csproj' and in the file 'ReflexilHost.xaml'. I am opening the solution on VS2013 Pro.

Could you check the source ?
Thanks

**Comment by tsviatko** [comment]
Could you, please, elaborate some more? What is the error message? Could we get a screenshot?

**Comment by Nonobis** [comment]
when i open directly "JustDecompile.ReflexilPlugin.sln" vs2013 report a conversion error.

![error1](https://cloud.githubusercontent.com/assets/3251510/8471244/9a8a4a20-2096-11e5-8367-b56662d329ef.png)

![error2](https://cloud.githubusercontent.com/assets/3251510/8471256/b82d45d2-2096-11e5-9f40-c42cc989c4ba.png)

**Comment by tsviatko** [comment]
Thank you very much for taking the time to report this issue. That is fixed now. Please, give it a try.

Once again thanks and sorry about the delay.

**Comment by Nonobis** [comment]
no problem :)
JustDecompile is a great apps, i will try this weekend.
Thanks again.
