### ISSUE TITLE
Publish JustDecompile.API to NuGet

### ISSUE THREAD

**Issue by alexanderkozlenko** [telerik/justdecompile-plugins#5]
It will be quite easier to consume plugins API assembly, if each public build of the application has corresponding JustDecompile.API assembly published to NuGet feed.

**Comment by tsviatko** [comment]
That is correct. I have added this to our backlog and we will do it at some point in the future. Thank you very much for the suggestion.

**Comment by atdimitrov** [comment]
Hi @alexanderkozlenko,

I'm very happy to inform you, that because of your suggestion we have now our API assembly available for download as NuGet package. Thank you and happy coding.

Best Regards,
Alexander
