### ISSUE TITLE
JustDecompile PowerTools project build error

### ISSUE THREAD

**Issue by alexanderkozlenko** [telerik/justdecompile-plugins#7]
1. MSB3245: Could not resolve this reference. Could not locate the assembly "JustDecompile.API".
2. CS7027: Error signing output with public key from file '..\..\GoToEntryPoint.snk' -- File not found.

**Comment by tsviatko** [comment]
You will find JustDecompile.API to the folder where JustDecompile is installed.

The GoToEntryPoint.snk was never intended to be there. It'd be really nice if you remove it from teh project and send us a pull request.
